### ISSUE TITLE
Patient Identiers

### ISSUE THREAD

**Issue by shadowdoc** [ImagingInformatics/hackathon-dataset#22]
Keep the original TCGA ID as the MRN - rename patients as follows:

BreastDx-01-0003 -> Sally SIIM
TCGA-17 -> Joe SIIM
TCGA-BA -> Neela SIIM
TCGA-50 ->  Andy SIIM
LIDC-IDRI-0132 -> Ravi SIIM

**Comment by chafey** [comment]
This is done
