### ISSUE TITLE
Error in upload: ruby upload.rb fhir_server.yml

### ISSUE THREAD

**Issue by paulorades** [ImagingInformatics/hackathon-dataset#63]
Hi. Sorry if this is not the right place.

I'm having trouble uploading resources. All previous steps have been successfully completed:

ruby upload.rb fhir_server.yml

Error:

upload.rb: 38: in `<main> ': usage: (RuntimeError)
ruby upload.rb server_config.yml path_for_recursion

Win10x64, 4GB RAM, 30GB HDD free
Ruby 2.4.4p296
JAVA 1.8.0_181 64bit JRE
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T05: 58: 13-02: 00)
Maven home: C: \ apache-maven-3.5.2 \ bin \ ..
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: C: \ Program Files \ Java \ jdk1.8.0_151 \ jre
Default locale: en_BR, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

Tks

**Comment by shadowdoc** [comment]
It’s hard to see in the readme - but there is a dot at the end of the line that specifies the current directory as the start for recursively finding the .json files to upload. 

ruby upload.rb fhir_server.yml .

I also realized there is a typo in the next line of the readme which should read:

ruby upload.rb fhir_server.yml siim_andy_tcga-50-5072/ DiagnosticReport

(The Yaml config file was omitted). Will fix this tomorrow. 

Marc
