### ISSUE TITLE
upload.rb logging issue

### ISSUE THREAD

**Issue by jturchetta** [ImagingInformatics/hackathon-dataset#64]
When running the upload.rb script for the SIIM  I received the following error: upload.rb:126:in `block (2 levels) in <main>': undefined method` []' for nil:NilClass (NoMethodError)

I discovered that when I comment out the following line: log.info("Submission Status: #{result["issue"][0]["diagnostics"]}") the script works. So something is off with is log.info line. Just thought I'd report this!

**Comment by shadowdoc** [comment]
Thanks for submitting this - I think that there were changes in the HAPI response.  I updated the logger to show the HTTP status code.
