### ISSUE TITLE
Upload script isn't working out of the box

### ISSUE THREAD

**Issue by mohannadhussain** [ImagingInformatics/hackathon-dataset#67]
Reported by Jon Turhcetta
When running the upload script, the line:
log.info("Submission status: #{result["issue"][0]["diagnostics"]}") has to be commented out, otherwise it throws a nil:Nilclass (noMethodError) error.

**Comment by shadowdoc** [comment]
I can't reproduce this one - I think that it's due to something in my local dev environment.  @mohannadhussain have you reproduced?

**Comment by mohannadhussain** [comment]
Not on macOS, I tried Ubuntu but bundler is crapping out for some reason. Either way, I can check with Jon to see if he's still having this issue and what environment he's using.

**Comment by mohannadhussain** [comment]
Closing because I can't reproduce this issue
