### ISSUE TITLE
compliance with TCIA Data Usage Policy

### ISSUE THREAD

**Issue by kirbyju** [ImagingInformatics/hackathon-dataset#83]
Hi, it appears there are datasets from The Cancer Imaging Archive being used in this repository.  While we're happy to see that they're being leveraged for this project we'd appreciate if you could please update [your readme.MD](https://github.com/ImagingInformatics/hackathon-dataset/blob/master/README.md) to provide attribution of the specific datasets that are being used in order to comply our data usage policy and give credit to the submitters who spent their time publishing the data.  Each TCIA dataset has its own dataset citation which you can find on the homepages for the datasets you've used.  If you have any questions about this I'd be happy to help answer them.

Best,
Justin

**Comment by mohannadhussain** [comment]
Hi Justin, thanks for catching that and bringing it to our attention. I've assigned this issue to myself and will work on getting the citations and will let you know if any questions come up.
